apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Prefixo para diferenciar os recursos de produção
namePrefix: prod-

# ATENÇÃO: Substitua SEU_USUARIO_DOCKER pelo seu usuário real do Docker Hub.
# Esta imagem é atualizada automaticamente pelo GitHub Actions a cada push na main.
images:
  - name: my-gitops-api:latest
    newName: docker.io/SEU_USUARIO_DOCKER/my-gitops-api
    newTag: v1.0.0  # Esta tag será sobrescrita pelo pipeline de CI/CD

# Produção roda com 3 réplicas para alta disponibilidade
replicas:
  - name: my-gitops-api
    count: 3
